version: '2'
services:
    app:
        container_name: symfony_app_1
        image: busybox:latest
        working_dir: /app
        volumes:
            - .:/app

    web:
        container_name: symfony_web_1
        build: docker/nginx
        working_dir: /app
        ports:
            - 80:80
        links:
            - php
        volumes_from:
            - app
        depends_on:
            - db
            - php

    php:
        container_name: symfony_php_1
        build: docker/php-fpm
        working_dir: /app
        volumes_from:
            - app
        links:
            - db
        depends_on:
            - app

    db:
        container_name: symfony_db_1
        image: mysql
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: symfony
            MYSQL_USER: symfony
            MYSQL_PASSWORD: symfony
        volumes_from:
            - db-data
        depends_on:
            - db-data

    db-data:
        container_name: symfony_dbdata_1
        image: busybox:latest
        volumes:
            - ./var/lib/mysql:/var/lib/mysql
